name: mkm
description: (Ming-Ke-Ming) Decentralized User Identity Authentication.
version: 0.1.0
repository: https://github.com/dimchat/mkm-dart

environment:
  sdk: '>=3.0.0-290.3.beta <4.0.0'

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
