name: mkm
description: Decentralized User Identity Authentication (Ming-Ke-Ming).
version: 1.1.1
homepage: https://github.com/dimchat/mkm-dart
repository: https://github.com/dimchat/mkm-dart
issue_tracker: https://github.com/dimchat/mkm-dart/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
