/* license: https://mit-license.org
 * =============================================================================
 * The MIT License (MIT)
 *
 * Copyright (c) 2023 Albert Moky
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 * =============================================================================
 */
import 'helpers.dart';
import 'keys.dart';
import 'public.dart';

/// Interface for asymmetric private keys (part of a key pair).
///
/// Private keys are used for:
/// - Decrypting data encrypted with the corresponding public key
/// - Generating digital signatures verifiable by the public key
///
/// Key data format (serialized as Map/JSON):
/// ```json
/// {
///   "algorithm" : "RSA",  // "ECC", ...
///   "data"      : "{BASE64_ENCODE}",
///   // Additional algorithm-specific parameters
///   // (e.g., key size, curve name)
/// }
/// ```
///
/// Implements [SignKey] for digital signature generation.
abstract interface class PrivateKey implements SignKey {

  /// Gets the [PublicKey] paired with this private key.
  ///
  /// The returned public key can be used to verify signatures generated by this private key,
  /// or to encrypt data that only this private key can decrypt.
  ///
  /// Returns: Corresponding [PublicKey] instance (non-null)
  PublicKey get publicKey;

  //
  //  Factory methods
  //

  static PrivateKey? generate(String algorithm) {
    var ext = CryptoExtensions();
    return ext.privateHelper!.generatePrivateKey(algorithm);
  }

  static PrivateKey? parse(Object? key) {
    var ext = CryptoExtensions();
    return ext.privateHelper!.parsePrivateKey(key);
  }

  static PrivateKeyFactory? getFactory(String algorithm) {
    var ext = CryptoExtensions();
    return ext.privateHelper!.getPrivateKeyFactory(algorithm);
  }
  static void setFactory(String algorithm, PrivateKeyFactory factory) {
    var ext = CryptoExtensions();
    ext.privateHelper!.setPrivateKeyFactory(algorithm, factory);
  }
}

/// Factory interface for creating and parsing [PrivateKey] instances.
///
/// Provides methods to generate new key pairs (private + public) and reconstruct
/// private keys from serialized data.
abstract interface class PrivateKeyFactory {

  /// Generates a new asymmetric key pair and returns the [PrivateKey].
  ///
  /// Uses the default algorithm (typically RSA) with secure random parameters.
  /// The corresponding public key can be accessed via [PrivateKey.publicKey].
  ///
  /// Returns: New cryptographically secure [PrivateKey] instance
  PrivateKey generatePrivateKey();

  /// Parses a serialized Map into a [PrivateKey] instance.
  ///
  /// [key]: Serialized private key data (matches the Map format defined in [PrivateKey])
  ///
  /// Returns: [PrivateKey] instance, or null if parsing/validation fails
  PrivateKey? parsePrivateKey(Map key);
}
